In [611]:
import torch
from importlib import reload
import sys
sys.path.append("/home/wu/Ubuntu/parallel_kinematics/")
import help as hp
reload(hp)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype= torch.float64
pi = torch.tensor(torch.pi,dtype=dtype)

In [612]:
r= torch.tensor([1.5,1,1.5],dtype=dtype)
R = hp.screw_matrix_y(pi/6)@hp.screw_matrix_x(pi/6)@hp.screw_matrix_z(pi/4)

para_bacward = hp.Parallel_backward(r,R,a = torch.tensor(0.5,dtype=dtype),b = torch.tensor(2.0,dtype=dtype),
                                l_1=torch.tensor(0.1,dtype=dtype),l_2= torch.tensor(0.15,dtype=dtype),theta = pi/6)
array_q = para_bacward.bacward_solver()
r_all_vector= para_bacward.gen_matrix_r_c()

r,R,
      

(tensor([1.5000, 1.0000, 1.5000], dtype=torch.float64),
 tensor([[ 0.7891, -0.4356,  0.4330],
         [ 0.6124,  0.6124, -0.5000],
         [-0.0474,  0.6597,  0.7500]], device='cuda:0', dtype=torch.float64))

In [613]:
test_for = hp.Parallel_forward(r,R,a = torch.tensor(0.5,dtype=dtype),b = torch.tensor(2.0,dtype=dtype),
                                l_1=torch.tensor(0.1,dtype=dtype),l_2= torch.tensor(0.15,dtype=dtype),
                            array_q=array_q,theta = pi/6)

#test_for.nonlinear_eqs(r_all_vector)
test_for.solver(r_all_vector)

(tensor([1.5000, 1.0000, 1.5000], device='cuda:0', dtype=torch.float64),
 tensor([[ 0.7891, -0.4356,  0.4330],
         [ 0.6124,  0.6124, -0.5000],
         [-0.0474,  0.6597,  0.7500]], device='cuda:0', dtype=torch.float64))